# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('tel', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cardid', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=45)),
                ('cardid', models.CharField(max_length=45)),
                ('roomtype', models.CharField(choices=[('standard', '\u6807\u51c6\u95f4'), ('better', '\u8c6a\u534e\u5957\u623f'), ('president', '\u603b\u7edf\u5957\u623f')], max_length=45)),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('totalprice', models.IntegerField()),
                ('state', models.CharField(choices=[('will', '\u9884\u5b9a\u4e2d'), ('run', '\u6267\u884c\u4e2d'), ('end', '\u5df2\u7ed3\u675f'), ('destroyed', '\u5df2\u5e9f\u5f03')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
